# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '借书证管理.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_card_manage(object):
    def setupUi(self, card_manage):
        card_manage.setObjectName("card_manage")
        card_manage.resize(500, 600)
        self.horizontalLayoutWidget = QtWidgets.QWidget(card_manage)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 80, 411, 240))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_1id = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_1id.setObjectName("label_1id")
        self.verticalLayout.addWidget(self.label_1id)
        self.label_1name = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_1name.setObjectName("label_1name")
        self.verticalLayout.addWidget(self.label_1name)
        self.label_1com = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_1com.setObjectName("label_1com")
        self.verticalLayout.addWidget(self.label_1com)
        self.label_1cla = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_1cla.setObjectName("label_1cla")
        self.verticalLayout.addWidget(self.label_1cla)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(card_manage)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 400, 411, 81))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2id = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2id.setObjectName("label_2id")
        self.horizontalLayout_2.addWidget(self.label_2id)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_2.addWidget(self.lineEdit_4)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.pushButton = QtWidgets.QPushButton(card_manage)
        self.pushButton.setGeometry(QtCore.QRect(340, 500, 112, 34))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(card_manage)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 340, 112, 34))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_1 = QtWidgets.QLabel(card_manage)
        self.label_1.setGeometry(QtCore.QRect(30, 40, 131, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(13)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(card_manage)
        self.label_2.setGeometry(QtCore.QRect(30, 360, 171, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(card_manage)
        QtCore.QMetaObject.connectSlotsByName(card_manage)

    def retranslateUi(self, card_manage):
        _translate = QtCore.QCoreApplication.translate
        card_manage.setWindowTitle(_translate("card_manage", "Form"))
        self.label_1id.setText(_translate("card_manage", "   卡号"))
        self.label_1name.setText(_translate("card_manage", "   姓名"))
        self.label_1com.setText(_translate("card_manage", "   单位"))
        self.label_1cla.setText(_translate("card_manage", "   类别"))
        self.comboBox.setItemText(0, _translate("card_manage", "学生"))
        self.comboBox.setItemText(1, _translate("card_manage", "教师"))
        self.comboBox.setItemText(2, _translate("card_manage", "其他"))
        self.label_2id.setText(_translate("card_manage", "   卡号"))
        self.pushButton.setText(_translate("card_manage", "删除"))
        self.pushButton_2.setText(_translate("card_manage", "添加"))
        self.label_1.setText(_translate("card_manage", "添加借书证"))
        self.label_2.setText(_translate("card_manage", "删除借书证"))

