# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homepage.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_homepage(object):
    def setupUi(self, homepage):
        homepage.setObjectName("homepage")
        homepage.resize(1000, 600)
        self.verticalLayoutWidget = QtWidgets.QWidget(homepage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 80, 831, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.admin_op = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.admin_op.setFont(font)
        self.admin_op.setObjectName("admin_op")
        self.verticalLayout1.addWidget(self.admin_op)
        self.horizontalLayout1_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_1.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout1_1.setSpacing(50)
        self.horizontalLayout1_1.setObjectName("horizontalLayout1_1")
        self.one_book_in_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.one_book_in_btn.setObjectName("one_book_in_btn")
        self.horizontalLayout1_1.addWidget(self.one_book_in_btn)
        self.card_manage_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.card_manage_btn.setObjectName("card_manage_btn")
        self.horizontalLayout1_1.addWidget(self.card_manage_btn)
        self.all_book_in_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.all_book_in_btn.setObjectName("all_book_in_btn")
        self.horizontalLayout1_1.addWidget(self.all_book_in_btn)
        self.verticalLayout1.addLayout(self.horizontalLayout1_1)
        self.verticalLayout1.setStretch(0, 2)
        self.verticalLayout1.setStretch(1, 2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(homepage)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(70, 260, 831, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout2.setObjectName("verticalLayout2")
        self.user_op = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.user_op.setFont(font)
        self.user_op.setObjectName("user_op")
        self.verticalLayout2.addWidget(self.user_op)
        self.horizontalLayout2_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout2_2.setSpacing(50)
        self.horizontalLayout2_2.setObjectName("horizontalLayout2_2")
        self.book_search_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.book_search_btn.setObjectName("book_search_btn")
        self.horizontalLayout2_2.addWidget(self.book_search_btn)
        self.lend_ben = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.lend_ben.setObjectName("lend_ben")
        self.horizontalLayout2_2.addWidget(self.lend_ben)
        self.return_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.return_btn.setObjectName("return_btn")
        self.horizontalLayout2_2.addWidget(self.return_btn)
        self.verticalLayout2.addLayout(self.horizontalLayout2_2)
        self.horizontalLayout2_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout2_1.setSpacing(50)
        self.horizontalLayout2_1.setObjectName("horizontalLayout2_1")
        self.log_search_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.log_search_btn.setObjectName("log_search_btn")
        self.horizontalLayout2_1.addWidget(self.log_search_btn)
        self.account_query_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.account_query_btn.setObjectName("account_query_btn")
        self.horizontalLayout2_1.addWidget(self.account_query_btn)
        self.lose_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.lose_btn.setObjectName("lose_btn")
        self.horizontalLayout2_1.addWidget(self.lose_btn)
        self.verticalLayout2.addLayout(self.horizontalLayout2_1)
        self.login_btn = QtWidgets.QPushButton(homepage)
        self.login_btn.setGeometry(QtCore.QRect(850, 20, 112, 34))
        self.login_btn.setObjectName("login")
        self.maxlabel = QtWidgets.QLabel(homepage)
        self.maxlabel.setGeometry(QtCore.QRect(370, 20, 231, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(18)
        self.maxlabel.setFont(font)
        self.maxlabel.setObjectName("maxlabel")

        self.retranslateUi(homepage)
        QtCore.QMetaObject.connectSlotsByName(homepage)

    def retranslateUi(self, homepage):
        _translate = QtCore.QCoreApplication.translate
        homepage.setWindowTitle(_translate("homepage", "Form"))
        self.admin_op.setText(_translate("homepage", "管理员操作"))
        self.one_book_in_btn.setText(_translate("homepage", "图书单本入库"))
        self.card_manage_btn.setText(_translate("homepage", "借书证管理"))
        self.all_book_in_btn.setText(_translate("homepage", "图书批量入库"))
        self.user_op.setText(_translate("homepage", "用户操作"))
        self.book_search_btn.setText(_translate("homepage", "图书查询"))
        self.lend_ben.setText(_translate("homepage", "借书"))
        self.return_btn.setText(_translate("homepage", "还书"))
        self.log_search_btn.setText(_translate("homepage", "借书信息查询"))
        self.account_query_btn.setText(_translate("homepage", "账户查询"))
        self.lose_btn.setText(_translate("homepage", "挂失"))
        self.login_btn.setText(_translate("homepage", "管理员登录"))
        self.maxlabel.setText(_translate("homepage", "图书管理系统"))

